name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Install PHP and its dependencies
      run: sudo sh ./bin/setup.sh
      if: always()    
      
    - name: Run the insaller (all stepp included)
      run: ./builds/installer run
      if: always()
      
    - uses: actions/download-artifact@v2
      with:
        path: /home/runner
    
    - name: Display structure of downloaded files
      if: always()      
      run: ls -R


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
