<?php

namespace Tests\Unit;

use Sculptor\Stages\Environment;
use Tests\TestCase;

/**
 * (c) Alessandro Cappellozza <alessandro.cappellozza@gmail.com>
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */
class EnvironmentTest extends TestCase
{
    private $env;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->env = new Environment([ 'a' => 10, 'b' => null ]);
    }

    public function testGet()
    {
        $this->assertEquals(10, $this->env->get('a'));

        $this->assertEquals('not found', $this->env->get('b', 'not found'));        
    }

    public function testHas()
    {
        $this->assertTrue($this->env->has('a'));

        $this->assertFalse($this->env->has('b'));        
    }

    public function testToArray()
    {
        $this->assertEquals([ 'a' => 10, 'b' => null ], $this->env->toArray());
    }    
}
