<?php

namespace Tests\Unit;

use Tests\Stubs\Version;
use Tests\TestCase;

/**
 * (c) Alessandro Cappellozza <alessandro.cappellozza@gmail.com>
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */
class VersionTest extends TestCase
{

    private $version;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->version = Version::make();
    }

    public function testVerificationBits()
    {
        $this->assertEquals('64', $this->version->bits());
    }

    public function testVerificationArch()
    {
        $this->assertEquals('x86_64', $this->version->arch());
    }

    public function testVerificationName()
    {
        $this->assertEquals('18.04.4 LTS (Bionic Beaver)', $this->version->name());
    }

    public function testVerificationCompatible()
    {
        $this->assertTrue($this->version->compatible(APP_COMPATIBLE_VERSION, APP_COMPATIBLE_ARCH));
    }

    public function testVerificationVersion()
    {
        $this->assertEquals('18.04', $this->version->version());
    }
}
