name: Release

on:
  push:
    #tags:
     # - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        composer_version: 1

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        composer_version: 1      
        command: php installer app:build --build-version=${{ steps.get_tag.outputs.VERSION }}
